# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Accueil
    url: '/'
    weight: 10
  - name: Projets
    weight: 20
    identifier: cours
  - name: Roller Dance Montpellier
    PageRef: c/roller/_index.md
    weight: 10
    parent: cours
  - name: Prépa Anglais
    PageRef: c/english/_index.md
    weight: 20
    parent: cours
  - name: Prépa Mathématiques
    PageRef: c/maths/_index.md
    weight: 30
    parent: cours
  - name: Prépa Physique-Chimie
    PageRef: c/physique-chimie/_index.md
    weight: 40
    parent: cours
  - name: Numérique et Ecologie
    PageRef: c/numerique-ecologie/_index.md
    weight: 50
    parent: cours
  - name: Vie Associative
    PageRef: asso/_index.md
    weight: 40
  - name: Blog
    PageRef: p/_index.md
    weight: 50
  - name: 
    params:
      rel: external
    pre: <i class="fa fa-heart"></i>
    url: https://www.helloasso.com/associations/maths-et-maryam
    weight: 60